name: Laravel Test Runner
author: halaslabs
description: "This action will run your Laravel application\'s test suite."

branding:
  color: 'purple'
  icon: 'crosshair'

inputs:
  php-version:
    description: 'PHP version to install'
    required: false
    default: '8.2'

runs:
  using: composite
  steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
      - run: |
          php -i
          php -m
          composer install --no-progress --prefer-dist --optimize-autoloader
          php artisan test
        shell: bash
