name: Laravel Test Runner
author: halaslabs
description: "This action will run your Laravel application\'s test suite."

branding:
  color: 'purple'
  icon: 'crosshair'

inputs:
  php-version:
    description: 'PHP version to install'
    required: false
    default: '8.2'

runs:
  using: composite
  steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
      - name: Install Dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
        shell: bash

      - name: Prepare
        run: |
          echo "::group::PHP Modules"
          php -m
          echo "::endgroup::"
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate
        shell: bash

      - name: Test Run
        run: |
          php artisan test
        shell: bash
