name: Laravel Test Runner
author: halaslabs
description: "This action will run your Laravel application's test suite."

branding:
  color: 'purple'
  icon: 'crosshair'

inputs:
  php-version:
    description: 'PHP version to install'
    required: false
    default: '8.2'
  setup:
    description: 'If false, setup-php will not be run and must be done prior to running this action'
    required: false
    default: "true"

runs:
  using: composite
  steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
        if: ${{ inputs.setup == "true" }}
      - name: Install Dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
        shell: bash

      - name: Prepare
        run: |
          echo "::group::PHP Modules"
          php -m
          echo "::endgroup::"
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate
        shell: bash

      - name: Test Run
        run: |
          php artisan test --without-tty | tee test_results
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat test_results >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        shell: bash
