name: 'Action Test'

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Default
    steps:
      - run: |
          docker run --rm \
          --pull=always \
          -v "$(pwd)":/laravel \
          -w /laravel \
          composer:latest \
          bash -c "composer create-project laravel/laravel action-test"
          ls -al
          ls -al action-test
      - uses: actions/checkout@v3
      - run: |
          ls -al
          ls -al action-test
      - uses: ./